config/routes.rb
Mpd::Application.routes.draw do

  resources :regions, :except => [:show]

  resources :periods, :shallow => true do
		member do
			get 'toggle_updated'
			post 'do_update'
		end

		resources :teams, :except => [:index, :new], :shallow => true do
			#resources :leaders, :as => 'team_leaders', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :groups, :except => [:index, :new], :shallow => true do
			resources :coaches, :as => 'group_coaches', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :admins, :as => 'period_admins', :only => [:show, :create, :destroy]
		member do
			get 'list'
			post 'list'
			get 'fields'
			post 'update_fields'
			get 'benchmarks'
			post 'update_benchmarks'
		end
	end

	resources :assignments, :except => :index, :shallow => true do
		resources :pledges, :only => [:index, :create, :destroy] do
			put 'toggle', :on => :member
		end
		resources :reports, :except => :index do
			collection do
				get 'list'
				post 'list'
			end
		end
		resources :goals
	end
  
  resources :users, :except => :index do
		get :confirm, :on => :member
		get :autocomplete, :on => :collection
		post :toggle_admin, :on => :member
		get :sudo, :on => :member
		get :unsudo, :on => :collection
	end

	match 'login' => 'home#login', :via => :get
	match 'login' => 'home#do_login', :via => :post
	match 'logout' => 'home#logout'
	match 'full_update' => 'home#full_update'
  match 'view_user' => 'home#view_user'
  match 'list' => 'home#list'
	
  # Shameless
  match 'backdoor' => 'home#backdoor'

	root :to => 'home#index'

	# Catch-all
	match '*uri' => 'home#not_found'
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :user_id, :period_id, :team_id, :group_id, :intern_type, :status

  def self.active
    Assignment.all.select{|a| a.active?}
  end

  def active?
    return ['accepted','placed','on_assignment','alumni'].include?(status)
  end

  belongs_to :user
  belongs_to :period
  belongs_to :group
  belongs_to :team
  has_many :pledges, :dependent => :destroy
  has_many :reports, :order => 'date DESC', :dependent => :destroy
  has_many :goals, :order => 'frequency', :dependent => :destroy

  validate do
    if group and period and group.period_id != period_id
      self.errors.add(:group_id, "group.period doesn't match period")
    end
    if team and period and team.period_id != period_id
      self.errors.add(:team_id, "team.period doesn't match period")
    end
  end

  def latest_report
    return nil if reports.count == 0
    return reports.first
  end

  def goal_amt(f)
    total = nil
    for goal in self.goals.select{|g| g.frequency == f}
      total = goal.amount
    end
    return total
  end

  def goal_pledged(f)
    pledges.not_in_hand.select{|p| p.frequency == f}.map{|p| p.amount}.sum
  end

  def goal_pledged_pct(f)
    Goal.pct(goal_pledged(f), goal_amt(f))
  end

  def goal_inhand(f)
    pledges.in_hand.select{|p| p.frequency == f}.map{|p| p.amount}.sum
  end
  
  def goal_inhand_pct(f)
    Goal.pct(goal_inhand(f), goal_amt(f))
  end

  def goal_total(f)
    pledges.select{|p| p.frequency == f}.map{|p| p.amount}.sum
  end
  
  def goal_total_pct(f)
    Goal.pct(goal_total(f), goal_amt(f))
  end

  def combined_pledged_pct
    amt = 0
    goal = 0
    for g in goals
      amt = amt + goal_pledged(g.frequency) * (g.frequency == 0 ? 1 : g.frequency)
      goal = goal + goal_amt(g.frequency) * (g.frequency == 0 ? 1 : g.frequency) if goal_amt(g.frequency)
    end
    return Goal.pct(amt, goal)
  end

  def combined_inhand_pct
    amt = 0
    goal = 0
    for g in goals
      amt = amt + goal_inhand(g.frequency) * (g.frequency == 0 ? 1 : g.frequency)
      goal = goal + goal_amt(g.frequency) * (g.frequency == 0 ? 1 : g.frequency) if goal_amt(g.frequency)
    end
    return Goal.pct(amt, goal)
  end

  def combined_total_pct
    amt = 0
    goal = 0
    for g in goals
      amt = amt + goal_total(g.frequency) * (g.frequency == 0 ? 1 : g.frequency)
      goal = goal + goal_amt(g.frequency) * (g.frequency == 0 ? 1 : g.frequency) if goal_amt(g.frequency)
    end
    return Goal.pct(amt, goal)
  end

  # Returns the number of unique names in pledges
  #   Used for building partners_lines
  def partners_count
    pledges.map{|p| p.name.strip}.uniq.count
  end

  def can_view?(u)
    return true if u.is_admin
    return true if u == self.user
    return true if period.admins.include?(u)
    return true if group and group.coaches.include?(u)
    return false
  end

  def can_edit?(u)
    return false if period.keep_updated
    return true if u.is_admin
    return true if u == self.user
    return true if period.admins.include?(u)
    return false
  end

  def can_view_pledges?(u)
    return true if can_edit_pledges?(u)
    return true if group and group.coaches.include?(u)
    return false
  end

  def can_edit_pledges?(u)
    return true if u.is_admin
    return true if u == self.user
    return true if period.admins.include?(u)
    return false
  end
  
  def can_view_reports?(u)
    can_view?(u)
  end
  
  def can_edit_reports?(u)
    return true if u.is_admin
    return true if u == self.user
    return true if period.admins.include?(u)
    return false
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  # GET /assignments/1
  def show
    if !@assignment = Assignment.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@assignment.can_view?(current_user)
      render 'shared/forbidden'
      return
    end
    member_breadcrumbs
  end

  # GET /assignments/1/edit
  def edit
    if !@assignment = Assignment.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@assignment.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    @new_goal = Goal.new
    member_breadcrumbs
  end

  # PUT /assignments/1
  def update
    if !@assignment = Assignment.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@assignment.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    valid = true

    params[:assignment][:team_id] = nil if params[:assignment][:team_id] == '0'
    params[:assignment][:group_id] = nil if params[:assignment][:group_id] == '0'

    for goal in @assignment.goals
      if params["remove_goal_#{goal.frequency}"] and params["remove_goal_#{goal.frequency}"] == '1'
        goal.destroy
      else
        params.select{|key, value| key == "goal_#{goal.frequency}"}.each do |key, value|
          goal.amount = Float(value[:amount])
        end
      end
    end

    if !params[:new_goal][:frequency].blank? and !params[:new_goal][:amount].blank?
      if params[:new_goal][:frequency] =~ /^\s*(\d+)\s*$/
        freq = $1
        if goal = @assignment.goals.find_by_frequency(freq)
          goal.amount = params[:new_goal][:amount]
        else
          goal = @assignment.goals.build(
            :frequency => freq,
            :amount => params[:new_goal][:amount]
            )
        end
        if !goal.save
          flash.alert = 'Could not create new Goal'
          valid = false
        end
      end
    end

    valid = false if valid and !@assignment.update_attributes(params[:assignment])

    if valid
      redirect_to @assignment, notice: 'Assignment updated'
    else
      member_breadcrumbs
      render action: 'edit'
    end
  end

  # POST /assignments/create
  def create
    assn = Assignment.new(params[:assignment])
    if !assn.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    continue = params[:continue] || request.referrer

    if params[:add_member].nil?
      flash.alert = 'Member not added'
      redirect_to continue
      return
    end

    # Adding a new user
    if params[:add_member][:new] == '1'
      if account_number = User.cleanup_account_number(params[:add_member][:account_number])
        if !old_user = User.find_by_account_number(account_number)
          if new_user = Sitrack.find_user(account_number)
            if new_user.save
              redirect_to(
                :controller => :users,
                :action => :confirm,
                :id => new_user.id,
                :continue => url_for(
                  :action => :create,
                  'assignment[period_id]' => assn.period_id,
                  'assignment[team_id]' => assn.team_id,
                  'assignment[group_id]' => assn.group_id,
                  'add_member[new]' => '0',
                  'add_member[user_id]' => new_user.id,
                  'continue' => request.referrer
                  )
                )
              return
            else
              flash.alert = 'Failed to save the new user'
            end
          else
            flash.alert = "No user found for account number: #{params[:add_member][:account_number]}"
          end
        else
          user_id = old_user.id
          # Fall through to existing user
        end
      else
        flash.notice = 'Member not added'
      end

      unless user_id # Some error occurred
        redirect_to continue
        return
      end

    # Adding an existing user
    else
      user_id = $1 if params[:add_member][:user_id] =~ /^(\d+)$/
    end

    if user_id.nil?
      flash.alert = 'No member selected'
    elsif !User.find_by_id(user_id)
      flash.alert = 'No user found'
    else
      assn.user_id = user_id
    end

    if assn.user_id.nil?
      redirect_to continue
      return
    end

    # Update group/team
    assns = assn.user.assignments.select{ |a| a.period and a.period.id == assn.period.id }
    if assns.count > 1
      throw "ERROR: No user should have two assignments in the same period"
    elsif assns.count == 1
      a = assns.first
      
      #NOTE: This doesn't warn the user if they switch someone's group or team
      a.team = assn.team if assn.team
      a.group = assn.group if assn.group

      assn = a
    end

    if assn.status.blank?
      # This should only happen in test regions, so we just want to make it visible
      assn.status = 'placed'
    end

    if assn.save
      flash.notice = 'Member added'
    else
      flash.alert = 'Member not added. An error occured while saving.'
    end

    redirect_to continue
  end

  # DELETE /assignments/1?delete=[group|team]
  def destroy
    if !assn = Assignment.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if assn.period.keep_updated? or !assn.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    if !params[:delete]
      u = assn.user
      if assn.destroy
        flash.notice = 'Assignment destroyed.'
        redirect_to u
      else
        flash.alert = 'Failed to delete assignment.'
        redirect_to assn
      end
      return
    elsif params[:delete] == 'group'
      assn.group = nil
    elsif params[:delete] == 'team'
      assn.team = nil
    else
      flash.alert = 'Nothing to delete'
      redirect_to :back
      return
    end

    if assn.group.nil? and assn.team.nil?
      # Don't delete the assignment automatically
    end

    if assn.save
      flash.notice = 'Member removed'
    else
      flash.alert = 'Member not removed: error while updating'
    end

    redirect_to :back
  end

  private
  # Adds breadcrumbs for all member views
  def member_breadcrumbs
    add_breadcrumb(@assignment.period.name, url_for(@assignment.period), @assignment.period.can_view?(current_user), 'Coaching Period')
    if @assignment.group 
      add_breadcrumb(@assignment.group.display_name, url_for(@assignment.group), @assignment.group.can_view?(current_user), 'Coaching Group')
    elsif @assignment.team
      add_breadcrumb(@assignment.team.display_name, url_for(@assignment.team), @assignment.team.can_view?(current_user), 'Team')
    end
    add_breadcrumb(@assignment.user.display_name, url_for(@assignment), true, 'Assignment')
  end

end

app/views/assignments/_list_data.xml.erb
<%= open_header %>
  <%= open_row %>
    <%= open_cell_head %>Name<%= close_cell_head %>
    <% if @fields['show_all'] == '1' -%>
      <%= open_cell_head %>Status<%= close_cell_head %>
    <% end -%>
    <% if @fields['intern_type'] == '1' -%>
      <%= open_cell_head %>Type<%= close_cell_head %>
    <% end -%>
    <% if @fields['group'] == '1' -%>
      <%= open_cell_head %>Group<%= close_cell_head %>
    <% end -%>
    <% if @fields['team'] == '1' -%>
      <%= open_cell_head %>Team<%= close_cell_head %>
    <% end -%>
    <%= open_cell_head %>Last Report<%= close_cell_head %>
<%# ### Goal information -%>
    <% for g in Goal.defaults -%>
      <% if @fields["#{g.frequency}_goal"] == '1' -%>
        <%= open_cell_head %><%= g.title %> Goal<%= close_cell_head %>
      <% end -%>
      <% if @fields["#{g.frequency}_inhand_pct"] == '1' -%>
        <%= open_cell_head %><%= "#{g.title} In-Hand Pct" %><%= close_cell_head %>
      <% end -%>
      <% if @fields["#{g.frequency}_inhand_amt"] == '1' -%>
        <%= open_cell_head %><%= "#{g.title} In-Hand Amt" %><%= close_cell_head %>
      <% end -%>
      <% if @fields["#{g.frequency}_pledged_pct"] == '1' -%>
        <%= open_cell_head %><%= "#{g.title} Pledged Pct" %><%= close_cell_head %>
      <% end -%>
      <% if @fields["#{g.frequency}_pledged_amt"] == '1' -%>
        <%= open_cell_head %><%= "#{g.title} Pledged Amt" %><%= close_cell_head %>
      <% end -%>
      <% if @fields["#{g.frequency}_total_pct"] == '1' -%>
        <%= open_cell_head %><%= "#{g.title} Total Pct" %><%= close_cell_head %>
      <% end -%>
    <% end -%>
<%# ### Goal combined percentages -%>
    <% if @fields['goal_combined_inhand'] == '1' -%>
      <%= open_cell_head %>Combined In-hand Pct<%= close_cell_head %>
    <% end -%>
    <% if @fields['goal_combined_pledged'] == '1' -%>
      <%= open_cell_head %>Combined Pledged Pct<%= close_cell_head %>
    <% end -%>
    <% if @fields['goal_combined_total'] == '1' -%>
      <%= open_cell_head %>Combined Total Pct<%= close_cell_head %>
    <% end -%>
<%# ### Report fields -%>
    <% if @fields['total_partners'] == '1' -%>
      <%= open_cell_head %>Number of Partners<%= close_cell_head %>
    <% end -%>
    <% for rf in @period.report_fields -%>
      <% if @fields["field_#{rf.id}"] == '1' -%>
        <%= open_cell_head %><%= rf.name %><%= close_cell_head %>
      <% end -%>
    <% end -%>
  <%= close_row %>
<%= close_header %>

<%= open_body %>
  <% for a in @assignments -%>
    <% r = a.latest_report -%>
    <%= open_row %>
      <%= open_cell_body %><%= link_to_if use_links, a.user.sort_name, a %><%= close_cell_body %>
      <% if !@assignment -%>
        <% if @fields[:show_all] == '1' -%>
          <%= open_cell_body %><%= a.status ? a.status : raw('') %><%= close_cell_body %>
        <% end -%>
        <% if @fields[:intern_type] == '1' -%>
          <%= open_cell_body %><%= a.intern_type ? a.intern_type : raw('') %><%= close_cell_body %>
        <% end -%>
        <% if @fields[:group] == '1' -%>
          <%= open_cell_body %><%= a.group ? link_to_if((use_links and a.group.can_view?(current_user)), a.group.display_name, a.group) : raw('') %><%= close_cell_body %>
        <% end -%>
        <% if @fields[:team] == '1' -%>
          <%= open_cell_body %><%= a.team ? link_to_if((use_links and a.team.can_view?(current_user)), a.team.display_name, a.team) : raw('') %><%= close_cell_body %>
        <% end -%>
      <% end -%>
      <%= open_cell_body %><%= r.nil? ? nil : link_to_if((use_links and a.can_view_reports?(current_user)), r.date.strftime('%Y %m/%d'), r) %><%= close_cell_body %>
<%# ### Goal information -%>
      <% for g in Goal.defaults -%>
        <% if @fields["#{g.frequency}_goal"] == '1' -%>
          <%= open_cell_body %><%= number_to_currency(a.goal_amt(g.frequency)) if a.goal_amt(g.frequency) %><%= close_cell_body %>
        <% end -%>
        <% if @fields["#{g.frequency}_inhand_pct"] == '1' -%>
<%
if r and l = r.goal_lines.find_by_frequency(g.frequency)
  val = view_pct( Goal.pct(l.inhand, a.goal_amt(g.frequency)) )
else
  val = nil
end
-%>
          <%= open_cell_body %><%= val %><%= close_cell_body %>
        <% end -%>
        <% if @fields["#{g.frequency}_inhand_amt"] == '1' -%>
<%
if r and l = r.goal_lines.find_by_frequency(g.frequency)
  val = number_to_currency(l.inhand)
else
  val = nil
end
-%>
          <%= open_cell_body %><%= val %><%= close_cell_body %>
        <% end -%>
        <% if @fields["#{g.frequency}_pledged_pct"] == '1' -%>
<%
if r and l = r.goal_lines.find_by_frequency(g.frequency)
  val = view_pct( Goal.pct(l.pledged, a.goal_amt(g.frequency)) )
else
  val = nil
end
-%>
          <%= open_cell_body %><%= val %><%= close_cell_body %>
        <% end -%>
        <% if @fields["#{g.frequency}_pledged_amt"] == '1' -%>
<%
if r and l = r.goal_lines.find_by_frequency(g.frequency)
  val = number_to_currency(l.pledged)
else
  val = nil
end
-%>
          <%= open_cell_body %><%= val %><%= close_cell_body %>
        <% end -%>
        <% if @fields["#{g.frequency}_total_pct"] == '1' -%>
<%
if r and l = r.goal_lines.find_by_frequency(g.frequency)
  val = view_pct( Goal.pct(l.inhand + l.pledged, a.goal_amt(g.frequency)) )
else
  val = nil
end
-%>
          <%= open_cell_body %><%= val %><%= close_cell_body %>
        <% end -%>
      <% end -%>
<%# ### Goal combined percentages -%>
<%
inhand_amt = nil
pledged_amt = nil
goal_amt = 0
# Don't display if the report is missing a goal_line
if r and r.goal_lines.count == a.goals.count
  inhand_amt = 0
  pledged_amt = 0
  for g in a.goals
    l = r.goal_lines.find_by_frequency(g.frequency)
    break unless l
    multiplier = (g.frequency == 0 ? 1 : g.frequency)
    inhand_amt = inhand_amt + l.inhand * multiplier
    pledged_amt = pledged_amt + l.pledged * multiplier
    goal_amt = goal_amt + a.goal_amt(g.frequency) * multiplier
  end
end
-%>
      <% if @fields['goal_combined_inhand'] == '1' -%>
        <%= open_cell_body %><%= view_pct(Goal.pct(inhand_amt, goal_amt)) if inhand_amt %><%= close_cell_body %>
      <% end -%>
      <% if @fields['goal_combined_pledged'] == '1' -%>
        <%= open_cell_body %><%= view_pct(Goal.pct(pledged_amt, goal_amt)) if pledged_amt %><%= close_cell_body %>
      <% end -%>
      <% if @fields['goal_combined_total'] == '1' -%>
        <%= open_cell_body %><%= view_pct(Goal.pct(inhand_amt + pledged_amt, goal_amt)) if inhand_amt and pledged_amt %><%= close_cell_body %>
      <% end -%>
<%# ### Report fields -%>
      <% if @fields['total_partners'] == '1' -%>
        <%= open_cell_body %><%= r.partners_line.total if r %><%= close_cell_body %>
      <% end -%>
      <% for rf in @period.report_fields -%>
        <% if @fields["field_#{rf.id}"] == '1' -%>
          <%= open_cell_body %><%= l.value if r and l = r.field_lines.find_by_report_field_id(rf.id) -%><%= close_cell_body %>
        <% end -%>
      <% end -%>
    <%= close_row %>
  <% end -%>
<%= close_body %>

app/views/assignments/edit.html.erb
<% title @assignment.user.display_name + ' - Assignment' %>

<div class="span6 offset3 well well-mini">
  <%= form_for @assignment do |f| %>
    Status
    <%= f.text_field :status %>
    <%= help_tip 'Possible values: on_assignment, Re-Applied, withdrawn, started, alumni, terminated, placed, declined, re-applied, accepted, etc.' %>

    <h3>Groups</h3>

    <% teams_array = [['None', 0]].concat( @assignment.period.teams.map { |t| [t.display_name, t.id] }) -%>
    Team: <%= f.select :team_id, options_for_select(teams_array, @assignment.team_id) %>
    <br>
    <% groups_array = [['None', 0]].concat( @assignment.period.groups.map { |g| [g.display_name, g.id] }) -%>
    Coaching group: <%= f.select :group_id, options_for_select(groups_array, @assignment.group_id) %>
    <br>
    <br>

    <h3>Goals</h3>

    <% for goal in @assignment.goals -%>
      <%= fields_for "goal_#{goal.frequency}", goal do |g| -%>
        <%= goal.title %> <%= g.text_field :amount, :size => 4 %>
        Delete: <%= check_box_tag "remove_goal_#{goal.frequency}" %>
        <br>
      <% end -%>
    <% end -%>
    <br>
    <%= fields_for "new_goal", @new_goal do |g| -%>
      <table class="table">
        <thead>
          <tr>
            <th colspan=2>
              New Goal
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Frequency</td>
            <td>
              <%= g.select :frequency, options_for_select([['',''], ['One-time', 0],['Monthly', 12]]) %>
            </td>
          </tr>
          <tr>
            <td>Amount</td>
            <td>
              <%= g.text_field :amount, :size => 4 %>
            </td>
          </tr>
        </tbody>
      </table>
    <% end -%>
    <br>
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', assignment_path(@assignment), class: 'btn' %>
  <% end -%>
</div>

app/views/assignments/show.html.erb
<% title @assignment.user.display_name + ' - Assignment' %>

<div class="span4">
<div class="well well-small">
  <h3>Details</h3>
  <table class="mytable">
    <tr>
      <th>User</th>
      <td>
        <%= link_to_if @assignment.user.can_view?(current_user), @assignment.user.display_name, @assignment.user %>
      </td>
    </tr>
    <tr>
      <th>Account Number</th>
      <td><%= @assignment.user.account_number %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= @assignment.user.phone %></td>
    </tr>
    <% if @assignment.intern_type -%>
      <tr>
        <th>Intern type</th>
        <td><%= @assignment.intern_type %></td>
      </tr>
    <% end -%>
    <tr>
      <th>Team</th>
      <td>
        <% if @assignment.team.nil? -%>
          <i>None</i>
        <% else -%>
          <%= link_to_if @assignment.team.can_view?(current_user), @assignment.team.display_name, @assignment.team %>
        <% end -%>
      </td>
    </tr>
    <tr>
      <th>Coaching Group</th>
      <td>
        <% if @assignment.group.nil? -%>
          <i>None</i>
        <% else -%>
          <%= link_to_if @assignment.group.can_view?(current_user), @assignment.group.display_name, @assignment.group %>
        <% end -%>
      </td>
    </tr>
    <% for goal in @assignment.goals -%>
      <tr>
        <th><%= goal.title %> goal</th>
        <td>
          <%= number_to_currency goal.amount %>
          <% if !goal.amount or goal.amount == 0 -%>
            <%= image_tag 'icons/silk/error.png', title: 'Percentages cannot be calculated for this goal' %>
          <% end -%>
        </td>
      </tr>
    <% end -%>
  </table>
  <% if @assignment.can_edit?(current_user) -%>
    <%= link_to 'Edit', edit_assignment_path(@assignment), class: 'btn' %>
    <% if !@assignment.period.keep_updated? -%>
      <%= link_to 'Delete', @assignment, method: 'delete', confirm: 'Are you sure you want to delete this assignment and all related pledges and reports?', class: 'btn btn-danger' %>
    <% end -%>
  <% end -%>

</div>

<% if @assignment.period.bmarks.count > 0 -%>
  <div class="well well-small">
    <h3>Benchmarks</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <% for b in @assignment.period.bmarks -%>
          <tr>
            <td><%= b.date.strftime('%b %e') %></td>
            <td><%= b.percentage %>%</td>
          </tr>
        <% end -%>
      </tbody>
    </table>
  </div>
<% end -%>

<% if @assignment.can_view_pledges?(current_user) and @assignment.goals.count > 0 -%>
  <div class="well well-small">
    <h3>Pledges</h3>
    <%= link_to 'View Pledges', assignment_pledges_path(@assignment) %>
    <br>
    <br>
    <table id='pledgePercent' class="table">
      <thead>
        <tr>
          <td></td>
          <th>In-hand</th>
          <th>With pledged</th>
        </tr>
      </thead>
      <tbody>
        <% for g in @assignment.goals -%>
          <tr>
            <th><%= g.title %></th>
            <% if g.amount and g.amount > 0 -%>
              <td><%= @assignment.goal_inhand_pct(g.frequency) %>%</td>
              <td><%= @assignment.goal_total_pct(g.frequency) %>%</td>
            <% else -%>
              <td><%= number_to_currency @assignment.goal_inhand(g.frequency) %></td>
              <td><%= number_to_currency @assignment.goal_total(g.frequency) %></td>
            <% end -%>
          </tr>
        <% end -%>
        <% if @assignment.goals.count > 1 -%>
          <tr>
            <th>Combined</th>
            <td><%= view_pct @assignment.combined_inhand_pct %></td>
            <td><%= view_pct @assignment.combined_total_pct %></td>
          </tr>
        <% end -%>
      </thead>
    </table>
  </div>
<% end -%>

</div>

<div class="span8 well well-small">
  <h3>Reports</h3>
  <table>
    <tr>
      <td><%= link_to 'New Report', new_assignment_report_path(@assignment), class: 'btn' if @assignment.can_edit_reports?(current_user) %></td>
      <td><%= link_to 'Report Details', list_assignment_reports_path(@assignment), class: 'btn' if @assignment.reports.count > 0 %></td>
    </tr>
  </table>

  <% if @assignment.reports.count > 0 -%>
    <table id='reportsTable' class="table">
      <thead>
        <tr>
          <td></td>
          <% for g in @assignment.goals -%>
            <th><%= g.title %> in-hand</th>
            <th><%= g.title %> total <%= help_tip 'Includes pledged' %></th>
          <% end -%>
        </tr>
      </thead>
      <tbody>
        <% for r in @assignment.reports -%>
          <tr>
            <th>
              <%= link_to r.date.strftime('%b %e'), r %>
              <% if r.can_delete?(current_user) -%>
                <%= link_to image_tag('icons/silk/delete.png'), r,
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this report?' } %>
              <% end -%>
            </th>
            <% for g in @assignment.goals -%>
              <% if l = r.goal_lines.find_by_frequency(g.frequency) -%>
                <% if !g.amount or g.amount == 0 -%>
                  <td><%= number_to_currency l.inhand %></td>
                  <td><%= number_to_currency l.inhand + l.pledged %></td>
                <% else -%>
                  <td><%= view_pct Goal.pct(l.inhand, @assignment.goal_amt(g.frequency)) %></td>
                  <td><%= view_pct Goal.pct(l.inhand + l.pledged, @assignment.goal_amt(g.frequency)) %></td>
                <% end -%>
              <% end -%>
            <% end -%>
          </tr>
        <% end -%>
      </tbody>
    </table>
  <% else -%>
    <i>None</i>
  <% end -%>

</div>