config/routes.rb
Mpd::Application.routes.draw do

  resources :regions, :except => [:show]

  resources :periods, :shallow => true do
		member do
			get 'toggle_updated'
			post 'do_update'
		end

		resources :teams, :except => [:index, :new], :shallow => true do
			#resources :leaders, :as => 'team_leaders', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :groups, :except => [:index, :new], :shallow => true do
			resources :coaches, :as => 'group_coaches', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :admins, :as => 'period_admins', :only => [:show, :create, :destroy]
		member do
			get 'list'
			post 'list'
			get 'fields'
			post 'update_fields'
			get 'benchmarks'
			post 'update_benchmarks'
		end
	end

	resources :assignments, :except => :index, :shallow => true do
		resources :pledges, :only => [:index, :create, :destroy] do
			put 'toggle', :on => :member
		end
		resources :reports, :except => :index do
			collection do
				get 'list'
				post 'list'
			end
		end
		resources :goals
	end
  
  resources :users, :except => :index do
		get :confirm, :on => :member
		get :autocomplete, :on => :collection
		post :toggle_admin, :on => :member
		get :sudo, :on => :member
		get :unsudo, :on => :collection
	end

	match 'login' => 'home#login', :via => :get
	match 'login' => 'home#do_login', :via => :post
	match 'logout' => 'home#logout'
	match 'full_update' => 'home#full_update'
  match 'view_user' => 'home#view_user'
  match 'list' => 'home#list'
	
  # Shameless
  match 'backdoor' => 'home#backdoor'

	root :to => 'home#index'

	# Catch-all
	match '*uri' => 'home#not_found'
  
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :region_id, :year, :keep_updated, :last_updated
  
  scope :updated, where(:keep_updated => true)

  belongs_to :region
  has_many :assignments, :dependent => :destroy
  has_many :reports, :through => :assignments
  has_many :groups, :dependent => :destroy
  has_many :teams, :dependent => :destroy
  has_many :period_admins, :dependent => :destroy
  has_many :admins, :through => :period_admins, :source => :user
  has_many :report_fields, :order => 'list_index', :dependent => :destroy
  has_many :bmarks, :order => 'date', :dependent => :destroy

  validate do
    report_fields.each do |f|
      f.errors.each do |attr, msg|
        self.errors.add(:report_fields, msg)
      end
    end
    bmarks.each do |b|
      b.errors.each do |attr, msg|
        self.errors.add(:bmarks, msg)
      end
    end
  end

  def name
    "#{region.display_name} #{year}"
  end

  def can_view?(u)
    return true if u.is_admin
    return true if admins.include?(u)
    return false
  end

  def can_edit?(u)
    return true if u.is_admin
    return true if admins.include?(u)
    return false
  end

end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController

  # GET /periods
  def index
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end
    @periods = Period.all.sort_by{|p| [-p.year, p.region.name]}
    @new_period = Period.new(:year => Date.today.year)
    @regions = Region.all
    @years = 2000..Date.today.year + 1
  end

  # POST /periods
  def create
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end

    if p = Period.find_by_region_id_and_year(params[:period][:region_id], params[:period][:year])
      flash.alert = "The period #{p.name} already exists"
    else
      @period = Period.new(params[:period])
      if @period.save
        flash.notice = "Period #{@period.name} created"

        # Download data
        if @period.keep_updated
          if Sitrack.update_period(@period)
            @period.last_updated = DateTime.now
            @period.save
          end
        end
      else
        flash.alert = 'An error occurred while saving'
      end
    end

    redirect_to :action => :index
  end

  # GET /periods/1
  def show
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_view?(current_user)
      render 'shared/forbidden'
      return
    end

    @new_group = Group.new
    @new_group.period = @period
    
    @new_team = Team.new
    @new_team.period = @period
    
    @new_admin = PeriodAdmin.new
    @new_admin.period = @period

    member_breadcrumbs
  end

  # DELETE /periods/1
  def destroy
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end

    if @period.destroy
      flash.notice = 'Period deleted'
    else
      flash.alert = 'Period not deleted'
    end

    redirect_to :action => :index
  end

  # GET /periods/1/toggle_updated
  def toggle_updated
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end

    @period.keep_updated = !@period.keep_updated

    if @period.save
      flash.notice = 'Period updated'
    else
      flash.notice = 'Failed to update period'
    end

    redirect_to :action => :index
  end

  # POST /periods/1/do_update
  def do_update
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    Sitrack.update_period(@period)

    redirect_to :back
  end

  # GET /periods/1/fields
  def fields
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_view?(current_user)
      render 'shared/forbidden'
      return
    end
    member_breadcrumbs
  end

  # POST /periods/1/update_fields
  def update_fields
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    valid = true

    # Update old fields
    for field in @period.report_fields
      id = "field_#{field.id}"
      if params[id]
        if params[id].delete('remove') == '1'
          valid = false if !field.destroy
        else
          valid = false if !field.update_attributes(params[id])
        end
      end
    end

    # Add new fields
    params.each do |key, hash|
      if key =~ /^newfield\_(\d+)/
        if hash.delete('remove') != '1'
          field = @period.report_fields.build(hash)
          valid = false if !field.save
        end
      end
    end

    if !valid
      member_breadcrumbs
      @period.valid? # Run validations
      render :action => :fields
    else
      flash.notice = 'Fields updated'
      redirect_to :action => :fields, :id => params[:id]
    end
  end

  # GET /periods/1/benchmarks
  def benchmarks
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_view?(current_user)
      render 'shared/forbidden'
      return
    end
    member_breadcrumbs
  end

  # POST /periods/1/update_benchmarks
  def update_benchmarks
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    valid = true

    # Update old benchmarks
    for bm in @period.bmarks
      id = "benchmark_#{bm.id}"
      if params[id]
        if params[id].delete('remove') == '1'
          valid = false if !bm.destroy
        else
          valid = false if !bm.update_attributes(params[id])
        end
      end
    end

    # Add new benchmarks
    params.each do |key, hash|
      if key =~ /^newbenchmark\_(\d+)/
        if hash.delete('remove') != '1'
          bm = @period.bmarks.build(hash)
          valid = false if !bm.save
        end
      end
    end

    if !valid
      @period.valid? #Run validations
      member_breadcrumbs
      render :action => :benchmarks
    else
      flash.notice = 'Benchmarks updated'
      redirect_to :action => :benchmarks, :id => params[:id]
    end
  end

  # GET /periods/1/list
  def list
    if !@period = Period.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@period.can_view?(current_user)
      render 'shared/forbidden'
      return
    end

    @list_title = "#{@period.name} Complete List"
    @list_type = 'period'
    @fields = params[:fields] || Hash.new

    if @fields[:show_all] == '1'
      @assignments = @period.assignments
    else
      @assignments = @period.assignments.active
    end
    @assignments = @assignments.sort_by{|a| a.user.sort_name}

    if params[:commit] == 'Download Excel'
      render 'assignments/list.xml', :content_type => 'application/xls'
      return
    end

    if params[:commit] == 'Clear'
      # Clear selections
      @fields = Hash.new
    end

    member_breadcrumbs
    render 'assignments/list', :layout => 'list'
  end

  private
  # Adds breadcrumbs for all member views
  def member_breadcrumbs
    add_breadcrumb(@period.name, url_for(@period), true, 'Coaching Period')
  end

end

app/views/periods/benchmarks.html.erb
<% title @period.name + ' - Benchmarks' %>

<% if @period.errors.any? -%>
  <% set_flash_from_block :error do -%>
      <%# HACK: I can't get rid of the "is invalid" errors -%>
      <% errors = @period.errors.select{|attr, msg| msg != "is invalid"} -%>
      <h4><%= pluralize(errors.count, 'error') %> prohibited this period from being saved:</h4>
      <ul>
        <% errors.each do |attr, msg| -%>
          <li><%= msg %></li>
        <% end -%>
      </ul>
  <% end -%>
<% end -%>

<% newBmarkId = 1 -%>

<div class="span8 offset2 well well-small">
  <%= form_for :benchmarks, :url => update_benchmarks_period_path(@period) do |f| %>
    <table id='benchmarksTable' class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Percentage</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% for bm in @period.bmarks -%>
<%
if bm.id
  bmark_id = "benchmark_#{bm.id}"
else
  # This happens if a new benchmark didn't save successfully
  bmark_id = "newbenchmark_#{newBmarkId}"
  newBmarkId = newBmarkId + 1
end
-%>
        <%= render :partial => 'benchmark_row', :locals => {:id => bmark_id, :bm => bm} %>
      <% end -%>
    </tbody>
    </table>

    <a href='javascript:void(0);' onclick="addRow();">Add Benchmark</a>
    <br>
    <br>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', @period, class: 'btn' %>
  <% end %>
</div>

<div style='display:none;'>
  <table>
  <%= render :partial => 'benchmark_row', :locals => {:id => "blankbenchmark", :bm => Bmark.new} %>
  </table>
</div>
    
<script type='text/javascript'>
function toggleDelete()
{
  var checked = this.checked;
  var rowId = this.id.substr(0,this.id.length-7)+'_row';
  var inputs = $('#'+rowId+' input, #'+rowId+' textarea, #'+rowId+ ' select');
  for (var i=0; i<inputs.length; i++)
  {
    if (!inputs[i].hidden && inputs[i].id != this.id)
      inputs[i].disabled = checked;
  }
}

function addRow()
{
  $('#blankbenchmark_row').clone().insertAfter('#benchmarksTable tr :last');
  var html = $('#benchmarksTable tr :last').html();
  var id = 'newbenchmark_'+newBmarkId;
  newBmarkId++;
  var idx = html.indexOf('blankbenchmark');
  while (idx > 0)
  {
    html = html.replace('blankbenchmark', id);
    idx = html.indexOf('blankbenchmark');
  }
  id = id + '_row';
  $('#benchmarksTable tr :last')[0].id = id;
  $('#'+id).html(html);
  $('#'+id)[0].cells[0].childNodes[1].value = $('#benchmarksTable tr').length-1;
  $('#'+id+' .remove_benchmark_box')[0].onchange = toggleDelete;
}

$(document).ready(function()
{
  var boxes = $('.remove_benchmark_box');
  for (var i=0; i < boxes.length; i++)
  {
    boxes[i].onchange = toggleDelete;
  }
  newBmarkId = <%= newBmarkId %>;
});
</script>

app/views/periods/fields.html.erb
<% title @period.name + ' - Report Fields' do -%>
<b>NOTE:</b>
<ul>
  <i>
  <li>You cannot edit the 'Type' of an existing field if a report has already been created for this period, since this could lead to data corruption. If you must make a change, you can delete the field and add it again, but you will lose all information that had been entered for that field.</li>
  </i>
</ul>
<% end -%>

<% if @period.errors.any? -%>
  <% set_flash_from_block :error do -%>
      <%# HACK: I can't get rid of the "is invalid" errors -%>
      <% errors = @period.errors.select{|attr, msg| msg != "is invalid"} -%>
      <h4><%= pluralize(errors.count, 'error') %> prohibited this period from being saved:</h4>
      <ul>
      <% errors.each do |attr, msg| -%>
          <li><%= msg %></li>
        <% end -%>
      </ul>
  <% end -%>
<% end -%>

<% newFieldId = 1 -%>

<div class="span12 well well-small">
  <%= form_for :fields, :url => update_fields_period_path(@period) do |f| %>
    <table id='fieldsTable' class="table">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Delete</th>
        <th>Type</th>
        <th>Required</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <%
        for rf in @period.report_fields
          if rf.id
            rf[:html_id] = "field_#{rf.id}"
          else
            # This happens if a new field didn't save successfully
            rf[:html_id] = "newfield_#{newFieldId}"
            newFieldId = newFieldId + 1
          end
        end
      -%>
      <% for rf in @period.report_fields.select{|field| field.list_index < 0} -%>
        <%= render :partial => 'field_row', :locals => {
          :id => rf.html_id,
          :rf => rf
          }
        %>
      <% end -%>
      <%= render :partial => 'field_row', :locals => {
        :id => 'goals',
        :rf => ReportField.new(:list_index => 0)
        }
      %>
      <% for rf in @period.report_fields.select{|field| field.list_index > 0} -%>
        <%= render :partial => 'field_row', :locals => {
          :id => rf.html_id,
          :rf => rf
          }
        %>
      <% end -%>
    </tbody>
    </table>

    <a href='javascript:void(0);' onclick="addRow();">Add Field</a>
    <br>
    <br>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', @period, class: 'btn' %>
  <% end %>
</div>

<div style='display:none;'>
  <table>
  <%= render :partial => 'field_row', :locals => {:id => 'blankfield', :rf => ReportField.new} %>
  </table>
</div>
    
<script type='text/javascript'>
function setListIndices()
{
  var rows = $('#fieldsTable tbody tr');
  var index = rows.length;
  for (var i=0; i<rows.length; i++)
  {
    console.log(rows[i].id);
    if (rows[i].id == 'goals_row')
    {
      index = i;
      break;
    }
  }
  if (index == rows.length)
  {
    // No goals_row tr
    //alert('no goals row!');
    var x = 1;
    for (var i=0; i<rows.length; i++)
    {
      rows[i].cells[0].childNodes[1].value = x;
      x = x+1;
    }
  }
  else
  {
    // Set indices for those above goals_row
    var x = -1;
    for (var i=index-1; i>=0; i--)
    {
      rows[i].cells[0].childNodes[1].value = x;
      x = x-1;
    }
    // Set indices for those below goals_row
    var x = 1;
    for (var i=index+1; i<rows.length; i++)
    {
      rows[i].cells[0].childNodes[1].value = x;
      x = x+1;
    }
  }
}
function reorder(id, dir)
{
  id = id + '_row';
  var rows = $('#fieldsTable tbody tr');
  var index = rows.length;
  for (var i=0; i < rows.length; i++)
  {
    if (rows[i].id == id)
    {
      index = i;
      break;
    }
  }
  if (index == rows.length) return; //invalid

  if (dir == 'up')
  {
    if (index == 0)
    {
      return; // At top
    }
    var otherId = rows[index - 1].id;
    $('#'+otherId).insertAfter('#'+id);
  }
  else if (dir == 'down')
  {
    if (index == rows.length - 1)
    {
      return; // At bottom
    }
    var otherId = rows[index + 1].id;
    $('#'+id).insertAfter('#'+otherId);
  }

  setListIndices();
};

function toggleDelete()
{
  var checked = this.checked;
  var rowId = this.id.substr(0,this.id.length-7)+'_row';
  var inputs = $('#'+rowId+' input, #'+rowId+' textarea, #'+rowId+ ' select');
  for (var i=0; i<inputs.length; i++)
  {
    if (!inputs[i].hidden && inputs[i].id != this.id)
      inputs[i].disabled = checked;
  }
}

function addRow()
{
  $('#blankfield_row').clone().insertAfter('#fieldsTable tr :last');
  var html = $('#fieldsTable tr :last').html();
  var id = 'newfield_'+newFieldId;
  newFieldId++;
  var idx = html.indexOf('blankfield');
  while (idx > 0)
  {
    html = html.replace('blankfield', id);
    idx = html.indexOf('blankfield');
  }
  id = id + '_row';
  $('#fieldsTable tr :last')[0].id = id;
  $('#'+id).html(html);
  $('#'+id+' .remove_field_box')[0].onchange = toggleDelete;

  setListIndices();
}

$(document).ready(function()
{
  var boxes = $('.remove_field_box');
  for (var i=0; i < boxes.length; i++)
  {
    boxes[i].onchange = toggleDelete;
  }
  newFieldId = <%= newFieldId %>;

  setListIndices();
});
</script>

app/views/periods/index.html.erb
<% title'Coaching Periods' %>

<div class="span4 well well-small">
  <h3>Create new Period</h3>
  <%= form_for @new_period do |f| -%>
    <table class="table">
      <tr>
        <td><%= f.label :region %></td>
        <td><%= f.select :region_id, @regions.sort_by{|r| r.display_name}.map{|r| [r.display_name, r.id]}, {}, class: 'span12' %></td>
      </tr>
      <tr>
        <td><%= f.label :year %></td>
        <td><%= f.select :year, @years, {}, class: 'span12' %></td>
      </tr>
      <tr>
        <td>
          Updated
          <%= help_tip 'If checked, SiTrack will be periodically pinged to keep the data up-to-date' %>
        </td>
        <td><%= f.check_box :keep_updated %></td>
      </tr>
      <tr>
        <td colspan="2">
          <%= f.submit class: 'btn btn-primary' %>
        </td>
      </tr>
    </table>
  <% end -%>
</div>

<div class="span8 well well-small">
  <% if @periods.count > 0 -%>
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Update</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% for p in @periods -%>
          <tr>
            <td><%= link_to p.name, p %></td>
            <td>
              <% if p.keep_updated -%>
                <%= link_to image_tag('icons/silk/accept.png'), toggle_updated_period_path(p), :title => 'Turn Off' %>
                <%= link_to 'Update', do_update_period_path(p), :method => :post %>
              <% else %>
                <%= link_to image_tag('icons/silk/exclamation.png'), toggle_updated_period_path(p), :title => 'Turn On' %>
              <% end -%>
            </td>
            <td>
              <% if p.keep_updated -%>
              <% end-%>
              <%= link_to image_tag('icons/silk/delete.png'), p, :method => :delete, :title => 'Delete', :confirm => 'Are you sure you want to delete this entire coaching period?' %>
            </td>
          </tr>
        <% end -%>
      </tbody>
    </table>
  <% else -%>
    <i>No Periods</i>
  <% end -%>
</div>

app/views/periods/show.html.erb
<% title @period.name do -%>
  <% if @period.keep_updated? -%>
Because this period is set to be updated periodically with data from Sitrack, you cannot change things such as team assignments and coaching assignments directly. You must first go to Sitrack and make the changes there, then come back here and click on "Manually Update".
  <% end -%>
<% end -%>

<div class="span4">
<div class="well well-small">
  <h3>Actions</h3>
  <ul>
    <li>
      <%= link_to "Show all people", list_period_path(@period)  %>
      (<%= @period.assignments.active.count %>)
    </li>
    <li>
      <%= link_to "Edit report fields", fields_period_path(@period) %>
      (<%= @period.report_fields.count %>)
    </li>
    <li>
      <%= link_to "Edit benchmarks", benchmarks_period_path(@period) %>
      (<%= @period.bmarks.count %>)
    </li>
    <% if @period.keep_updated? -%>
      <li>
          <%= link_to 'Manually Update', do_update_period_path(@period), method: 'post' %>
          (Last Updated: <%= @period.last_updated ? @period.last_updated.strftime('%B %e, %Y at %I:%M %p') : raw('<i>Never</i>') %>)
      </li>
    <% end -%>
  </ul>

</div>
<div class="well well-small">

  <h3>Administrators</h3>
  <% if @period.admins.nil? or @period.admins.count == 0 -%>
    <i>None</i>
  <% else -%>
    <ul>
      <% for a in @period.period_admins.sort_by{|a| a.user.sort_name} -%>
        <li>
          <%= link_to_if a.user.can_view?(current_user), a.user.display_name, a.user %>
          <% if @period.can_edit?(current_user) -%>
            <%= link_to image_tag('icons/silk/delete.png'), a, method: :delete, data: { confirm: 'Are you sure you want to remove this admin?' } %>
          <% end -%>
        </li>
      <% end -%>
    </ul>
  <% end -%>
  <% if @period.can_edit?(current_user) -%>
    <%= form_for [@period, @new_admin] do |f| -%>
      <%= render :partial => 'users/new', :locals => {
        :name => 'add_admin',
        :title => 'New Admin',
        :commit => 'Add Admin' } %>
    <% end -%>
  <% end -%>
</div>
</div>

<div class="span4 well well-small">
  <h3>Teams</h3>
  <% if @period.teams.active.count == 0 -%>
    <i>None</i>
  <% else -%>
    <ul>
      <% for t in @period.teams.active.sort_by{|t| t.display_name} -%>
        <li>
          <%= link_to t.display_name, t %>
          (<%= pluralize t.assignments.active.count, 'member' %>)
          <% if t.assignments.count == 0 and @period.can_edit?(current_user) and !@period.keep_updated? -%>
            <%= link_to image_tag('icons/silk/delete.png'), t, method: :delete, data: { confirm: 'Are you sure you want to delete this team?' } %>
          <% end -%>
        </li>
      <% end -%>
    </ul>
  <% end -%>
  <% if @period.can_edit?(current_user) and !@period.keep_updated? -%>
    <%= form_for [@period, @new_team] do |f| -%>
      <%= f.text_field :name, :size => 12 %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end -%>
  <% end -%>
</div>

<div class="span4 well well-small">
  <h3>Coaching Groups</h3>
  <% if @period.groups.active.count == 0 -%>
    <i>None</i>
  <% else -%>
    <ul>
      <% for g in @period.groups.active.sort_by{|g| g.display_name} -%>
        <li>
          <%= link_to g.display_name, g %>
          <% if g.coaches.count == 0 -%>
            <%= image_tag 'icons/silk/error.png', title: 'No coach has been assigned to this group.' %>
          <% end -%>
          (<%= pluralize g.assignments.active.count, 'member' %>)
          <% if g.assignments.count == 0 and @period.can_edit?(current_user) and !@period.keep_updated? -%>
            <%= link_to image_tag('icons/silk/delete.png'), g, method: :delete, title: 'Delete', data: { confirm: 'Are you sure you want to delete this group?' } %>
          <% end -%>
        </li>
      <% end -%>
    </ul>
  <% end -%>
  <% if @period.can_edit?(current_user) and !@period.keep_updated? -%>
    <%= form_for [@period, @new_group] do |f| -%>
      <%= f.text_field :name, :size => 12 %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end -%>
  <% end -%>
</div>

app/views/periods/show_fields.html.erb
<%= page_header 'Report Fields (' + @period.name + ')' do %>
Report Fields (<%= link_to @period.name, @period %>)
<% end -%>
<%= flash_header %>

<div class="grid_12">
	<b>NOTE:</b>
	<ul>
		<i>
		<li>Lines are automatically added for goal progress, two for each goal (e.g. "Monthly pledged" and "Monthly in-hand").</li>
		<li>You cannot edit the 'Type' of an existing field if a report has already been created for this period, since this could lead to data corruption. If you must make a change, you can delete the field and add it again, but you will lose all information that had been entered for that field.</li>
		</i>
	</ul>
	<%= form_for :fields, :url => update_fields_period_url(@period) do |f| %>
		<table id='fieldsTable' class='description'>
		<thead>
			<tr>
				<th></th>
				<th>Name</th>
				<th>Delete</th>
				<th>Type</th>
				<th>Required</th>
				<th>Description</th>
			</tr>
		</thead>
		<tbody>
			<% for rf in @period.report_fields %>
				<%= render :partial => 'field_row', :locals => {:id => "field_#{rf.id}", :rf => rf} %>
			<% end %>
		</tbody>
		</table>
		
		<a href='javascript:void(0);' onclick="addRow();">Add Field</a>
		<%= f.submit 'Save' %>
		<%= link_to 'Back', @period %>
	<% end %>
</div>

<div class="clear"></div>

<div style='display:none;'>
	<table>
	<%= render :partial => 'field_row', :locals => {:id => 'blankfield', :rf => ReportField.new} %>
	</table>
</div>
		
<script type='text/javascript'>
function reorder(id, dir)
{
	id = id + '_row';
	var rows = $('#fieldsTable tr');
	var index = rows.length; //invalid
	for (var i = 1; i < rows.length; i++)
	{
		if (rows[i].id == id)
		{
			index = i;
			break;
		}
	}
	if (index == rows.length) return; //invalid

	if (dir == 'up')
	{
		if (index == 1)
		{
			//alert("can't!");
			return;
		}
		rows[index].cells[0].childNodes[1].value = index - 1;
		rows[index - 1].cells[0].childNodes[1].value = index;
		var otherId = rows[index - 1].id;
		$('#'+otherId).insertAfter('#'+id);
	}
	else if (dir == 'down')
	{
		if (index == rows.length - 1)
		{
			//alert("can't!");
			return;
		}
		rows[index].cells[0].childNodes[1].value = index + 1;
		rows[index + 1].cells[0].childNodes[1].value = index;
		var otherId = rows[index + 1].id;
		$('#'+id).insertAfter('#'+otherId);
	}
};

function toggleDelete()
{
	var checked = this.checked;
	var rowId = this.id.substr(0,this.id.length-7)+'_row';
	var inputs = $('#'+rowId+' input, #'+rowId+' textarea, #'+rowId+ ' select');
	for (var i=0; i<inputs.length; i++)
	{
		if (!inputs[i].hidden && inputs[i].id != this.id)
			inputs[i].disabled = checked;
	}
}

function addRow()
{
	$('#blankfield_row').clone().insertAfter('#fieldsTable tr :last');
	var html = $('#fieldsTable tr :last').html();
	var id = 'newfield_'+newFieldId;
	newFieldId++;
	var idx = html.indexOf('blankfield');
	while (idx > 0)
	{
		html = html.replace('blankfield', id);
		idx = html.indexOf('blankfield');
	}
	id = id + '_row';
	$('#fieldsTable tr :last')[0].id = id;
	$('#'+row).html(html);
	$('#'+row).cells[0].innerNodes[1].value = $('#fieldsTable tr').length-1;
	$('#'+id)[0].onchange = toggleDelete;
}

$(document).ready(function()
{
	var boxes = $('.remove_field_box');
	for (var i=0; i < boxes.length; i++)
	{
		boxes[i].onchange = toggleDelete;
	}
	newFieldId = 1;
});
</script>