config/routes.rb
Mpd::Application.routes.draw do

  resources :regions, :except => [:show]

  resources :periods, :shallow => true do
		member do
			get 'toggle_updated'
			post 'do_update'
		end

		resources :teams, :except => [:index, :new], :shallow => true do
			#resources :leaders, :as => 'team_leaders', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :groups, :except => [:index, :new], :shallow => true do
			resources :coaches, :as => 'group_coaches', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :admins, :as => 'period_admins', :only => [:show, :create, :destroy]
		member do
			get 'list'
			post 'list'
			get 'fields'
			post 'update_fields'
			get 'benchmarks'
			post 'update_benchmarks'
		end
	end

	resources :assignments, :except => :index, :shallow => true do
		resources :pledges, :only => [:index, :create, :destroy] do
			put 'toggle', :on => :member
		end
		resources :reports, :except => :index do
			collection do
				get 'list'
				post 'list'
			end
		end
		resources :goals
	end
  
  resources :users, :except => :index do
		get :confirm, :on => :member
		get :autocomplete, :on => :collection
		post :toggle_admin, :on => :member
		get :sudo, :on => :member
		get :unsudo, :on => :collection
	end

	match 'login' => 'home#login', :via => :get
	match 'login' => 'home#do_login', :via => :post
	match 'logout' => 'home#logout'
	match 'full_update' => 'home#full_update'
  match 'view_user' => 'home#view_user'
  match 'list' => 'home#list'
	
  # Shameless
  match 'backdoor' => 'home#backdoor'

	root :to => 'home#index'

	# Catch-all
	match '*uri' => 'home#not_found'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :guid, :account_number, :first_name, :last_name, :preferred_name, :phone, :email, :is_admin, :time_zone, :last_login, :real_id

  scope :has_guid, where("guid IS NOT NULL")
  scope :admin, where(:is_admin => true)

  belongs_to :real_user, :class_name => "User", :foreign_key => :real_id

  has_many :assignments, :dependent => :destroy
  has_many :group_coaches, :dependent => :destroy
  has_many :team_leaders, :dependent => :destroy
  has_many :period_admins, :dependent => :destroy

  has_many :groups_as_member, :through => :assignments, :source => :group, :order => "name"
  has_many :groups_as_coach, :through => :group_coaches, :source => :group, :order => "name"
  has_many :teams_as_member, :through => :assignments, :source => :team, :order => "name"
  has_many :teams_as_leader, :through => :team_leaders, :source => :team, :order => "name"
  has_many :periods_as_admin, :through => :period_admins, :source => :period

  validate do
    self.guid = User.cleanup_guid(self.guid)
    self.account_number = User.cleanup_account_number(self.account_number)

    if !self.guid and !self.account_number
      # Don't allow both to be nil
      self.errors.add(:guid, 'Must set either valid guid or valid account_number')
    end
  end

  validates_each :first_name, :last_name, :preferred_name, :phone, :email do |record, attr, value|
    record[attr] = nil if value.nil? or value.blank?
  end

  validates :email, :format => { 
    :with => /^[_A-Za-z0-9-]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[A-Za-z]{2,4})$/,
    :allow_nil => true,
    :allow_blank => true, #Overwritten by above validation
    :message => "Invalid format"
    }

  validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.zones_map(&:name), :allow_nil => true

  validates_each :real_id do |record, attr, value|
    if value and User.find_by_id(value) == record
      record.errors.add(:real_id, ' - cannot merge a user into itself.')
    end
  end

  # Turns value into a valid guid or nil
  def self.cleanup_guid(value)
    return nil if value.nil? or value.blank?
    return value if value =~ /^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$/
    return nil
  end

  # Turns value into a valid account_number or nil
  def self.cleanup_account_number(value)
    return nil if value.nil? or value.blank?
    return "00#{$2}#{$3}" if value.strip =~ /^(00|)(\d{7})(S|)$/
    return nil
  end

  def display_name
    f = preferred_name || first_name
    l = last_name
    return "##{account_number}"  if !f and !l
    return l if !f
    return f if !l
    return "#{f} #{l}"
  end

  def sort_name
    f = preferred_name || first_name
    l = last_name
    return "##{account_number}"  if !f and !l
    return l if !f
    return f if !l
    return "#{l}, #{f}"
  end


  # Return all periods with which this user is affiliated
  def all_periods
    res = Array.new
    res.concat periods_as_admin
    res.concat assignments.map{|a| a.period}
    res.concat groups_as_coach.map{|g| g.period}
    #res.concat teams_as_leader.map{|t| t.period}
    return res.uniq
  end
  
  def can_view?(u)
    return true
  end

  def can_edit?(u)
    return true if u.is_admin
    return true if u == self

    for p in all_periods
      return true if p.admins.include?(u)
    end

    return false
  end

  # Can't edit certain fields if they are a part of an updated Period
  def gets_updated?
    for p in all_periods
      return true if p.keep_updated?
    end
    return false
  end

  # Returns true if u can become self
  def can_sudo?(u)
    return true if u.is_admin?
#    for p in all_periods
#      return true if p.admins.include?(u)
#    end

    return false
  end

  def self.autocomplete_help_tip_text
    "This is an autocomplete field. Type in the user's name or account number."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  if Rails.env.development?
    # Used in the development login screen
    skip_before_filter :authorize, :only => :autocomplete
  end

  # GET /users/1
  def show
    if !@user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@user.can_view?(current_user)
      render 'shared/forbidden'
      return
    end
  end

  # GET /users/1/edit
  def edit
    if !@user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@user.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end
  end

  # PUT /users/1
  def update
    if !@user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !@user.can_edit?(current_user)
      render 'shared/forbidden'
      return
    end

    # Only change allowed fields

    @user.time_zone = params[:user][:time_zone]

    if !@user.gets_updated?
      @user.preferred_name = params[:user][:preferred_name]
      @user.last_name = params[:user][:last_name]
      @user.phone = params[:user][:phone]
      @user.email = params[:user][:email]
    end

    if current_user.is_admin?
      if params[:real_user][:name].blank?
        @user.real_id = nil
      else
        @user.real_id = params[:user][:real_id]
      end
    end

    if @user.save
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /users/1
  def destroy
    if !@user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end

    @user.destroy

    redirect_to :controller => :home, :action => :index
  end

  # GET /users/1/confirm
  def confirm
    if !@user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end
    @continue_path = params[:continue]
  end

  # GET /users/autocomplete
  def autocomplete
    results = Array.new

    # TODO
    # Do I need to filter?
    # This is slow
    for user in User.all
      if user.account_number and !user.account_number.blank?
        string = "#{user.display_name} (#{user.account_number})"
      else
        string = user.display_name
      end
      if string.downcase =~ /#{params[:term].downcase}/
        results << {:id => user.id, :label => string, :value => user.display_name}
      end
    end

    render :json => results.sort_by{|r| r[:label]}[0..9].to_json
  end

  # POST /users/1/toggle_admin
  def toggle_admin
    if !user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end

    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end

    user.is_admin = !user.is_admin
    user.save

    redirect_to :user, :notice => 'User updated.'
  end

  # GET /users/1/sudo
  def sudo
    if !user = User.find_by_id(params[:id])
      render 'shared/not_found'
      return
    end

    true_user = sudo_user || current_user
    if !user.can_sudo?(true_user)
      render 'shared/forbidden'
      return
    end

    session[:sudo_id] = user.id

    redirect_to user
  end

  # GET /users/unsudo
  def unsudo
    session[:sudo_id] = nil
    redirect_to :back
  end

end

app/views/users/_form.html.erb
<%= form_for @user, :html => {class: 'form-horizontal'} do |f| %>
  <% if @user.errors.any? %>
    <% set_flash_from_block :error do -%>
      <h4><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h4>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    <% end -%>
  <% end -%>

  <% disabled = @user.gets_updated? -%>
  <% locked_text = 'This attribute is updated automatically.' -%>

  <div class="control-group">
    <%= f.label :first_name, class: 'control-label' %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :first_name, :disabled => disabled %>
        <% if disabled -%>
          <span class="add-on">
            <%= image_tag 'icons/silk/error.png', title: locked_text %>
          </span>
        <% end -%>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :preferred_name, class: 'control-label' %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :preferred_name, :disabled => disabled %>
        <% if disabled -%>
          <span class="add-on">
            <%= image_tag 'icons/silk/error.png', title: locked_text %>
          </span>
        <% end -%>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, class: 'control-label' %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :last_name, :disabled => disabled %>
        <% if disabled -%>
          <span class="add-on">
            <%= image_tag 'icons/silk/error.png', title: locked_text %>
          </span>
        <% end -%>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, class: 'control-label' %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :phone, :disabled => disabled %>
        <% if disabled -%>
          <span class="add-on">
            <%= image_tag 'icons/silk/error.png', title: locked_text %>
          </span>
        <% end -%>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :email, :disabled => disabled %>
        <% if disabled -%>
          <span class="add-on">
            <%= image_tag 'icons/silk/error.png', title: locked_text %>
          </span>
        <% end -%>
      </div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :time_zone, class: 'control-label' %>
    <div class="controls">
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
    </div>
  </div>

  <% if current_user.is_admin? -%>
    <div class="control-group">
      <%= label_tag :real_user_name, 'Real user', class: 'control-label' %>
      <div class="controls">
        <%= f.hidden_field :real_id %>
        <div class="input-append">
          <%= autocomplete_field 'real_user', 'name', autocomplete_users_path, :id_element => '#user_real_id', :value => (@user.real_user ? @user.real_user.display_name : nil) %>
          <span class="add-on">
            <%= help_tip User.autocomplete_help_tip_text %>
          </span>
        </div>
      </div>
    </div>
  <% end -%>

  <div class="control-group">
    <div class="controls">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', user_path(@user), class: 'btn' %>
    </div>
  </div>
<% end -%>

app/views/users/_new.html.erb
<%= hidden_field name, :user_id %>
<table class="table">
  <thead>
    <th colspan="3" style="text-align:center;"><%= title %></th>
  </thead>
  <tbody>
    <tr>
      <td>Existing User</td>
      <td><%= radio_button name, 'new', '0', :checked => true %></td>
      <td>
        <div class="input-append">
          <%= autocomplete_field name, :name, autocomplete_users_path, :id_element => "##{name}_user_id", class: 'input-small' %>
          <div class="add-on">
            <%= help_tip User.autocomplete_help_tip_text %>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>New User</td>
      <td><%= radio_button name, 'new', '1' %></td>
      <td>
        <div class="input-append">
          <%= text_field name, :account_number, :disabled => true, class: 'input-small' %>
          <div class="add-on">
            <%= help_tip 'Use their account number. You will be prompted on the next screen to confirm the selected user.' %>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <th colspan="3" style="text-align:center;">
        <%= submit_tag commit, class: 'btn btn-primary' %>
      </th>
    </tr>
  </tbody>
</table>

<script>
    $("[name='<%= name %>[new]']").click(function() {
      if ($("[name='<%= name %>[new]']:checked").val() == '0')
      {
          $('#<%= name %>_name')[0].disabled = false;
          $('#<%= name %>_account_number')[0].disabled = true;
      }
      else
      {
          $('#<%= name %>_name')[0].disabled = true;
          $('#<%= name %>_account_number')[0].disabled = false;
      }
    });
</script>

app/views/users/_roles.html.erb
<% showed_something = false -%>
<% if @user.assignments.active.count > 0 -%>
  <h3>Assignments</h3>
  <ul>
    <% for a in @user.assignments.active.sort_by{|a| [-a.period.year, a.period.region.name]} -%>
      <li><%= link_to_if a.period.can_view?(current_user), a.period.name, a.period %>
      <ul>
        <% if a.can_view?(current_user) %><li>Assignment: <%= link_to 'Home Page', a %></li><% end -%>
        <% if a.team %><li>Team: <%= link_to_if a.team.can_view?(current_user), a.team.display_name, a.team %></li><% end %>
        <% if a.group %><li>Coaching Group: <%= link_to_if a.group.can_view?(current_user), a.group.display_name, a.group %></li><% end %>
      </ul>
      <br>
      </li>
    <% end -%>
  </ul>
  <% showed_something = true -%>
<% end -%>
<% if @user.groups_as_coach.count > 0 -%>
  <h3>Coaching Groups</h3>
  <ul>
    <% for g in @user.groups_as_coach.sort_by{|g| [-g.period.year, g.period.region.name]} -%>
      <li><%= link_to_if g.period.can_view?(current_user), g.period.name, g.period %>
      <ul>
        <li><%= link_to_if g.can_view?(current_user), g.display_name, g %></li>
      </ul>
    <% end -%>
  </ul>
  <% showed_something = true -%>
<% end -%>
<% if @user.periods_as_admin.count > 0 -%>
  <h3>Coaching Periods</h3>
  <ul>
    <% for p in @user.periods_as_admin.sort_by{|p| [-p.year, p.region.name]} -%>
      <li><%= link_to_if p.can_view?(current_user), p.name, p %></li>
    <% end -%>
  </ul>
  <% showed_something = true -%>
<% end -%>
<% if !showed_something %>
  <h4>No Active Roles</h4>
  <i>If you believe you ought to have a role, please use the link at the bottom of the page to notify the webmaster.</i>
<% end -%>

app/views/users/confirm.html.erb
<% title 'Add New User' %>

<div class="span8 offset2 well well-small">
  <%= form_for @user, :url => @continue_path, :method => :post do |f| %>
    <table class="table">
      <tr>
        <th>Account Number</th>
        <td>
          <%= @user.account_number %>
        </td>
      </tr>
      <tr>
        <th>First Name</th>
        <td>
          <%= @user.first_name %>
        </td>
      </tr>
      <tr>
        <th>Preferred Name</th>
        <td>
          <%= @user.preferred_name %>
        </td>
      </tr>
      <tr>
        <th>Last Name</th>
        <td>
          <%= @user.last_name %>
        </td>
      </tr>
      <tr>
        <th>Phone Number</th>
        <td>
          <%= @user.phone %>
        </td>
      </tr>
      <tr>
        <th>Email Address</th>
        <td>
          <%= @user.email %>
        </td>
      </tr>
    </table>
    <%= f.submit 'Confirm', class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn' %>
  <% end -%>
</div>

app/views/users/edit.html.erb
<% title @user.display_name + ' - Edit' do -%>
  <% if @user.gets_updated? -%>
Because of this user's assignments, some of these attributes are automatically updated and thus blocked here. If you believe there is an error with one or more of these fields, please notify your regional coordinator.
  <% end -%>
<% end -%>

<div class="span6 offset3 well well-small">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% title @user.display_name do -%>
  <% if @user.real_user -%>
    NOTE: This account has been merged into <%= link_to @user.real_user.display_name, @user.real_user %>'s account.
  <% end -%>
<% end -%>

<div class="span4 well well-small">
  <table class="mytable">
    <tr>
      <th>First Name</th>
      <td><%= @user.first_name %></td>
    </tr>
    <% if @user.preferred_name and @user.preferred_name != @user.first_name -%>
      <tr>
        <th>Preferred Name</th>
        <td><%= @user.preferred_name %></td>
      </tr>
    <% end -%>
    <tr>
      <th>Last Name</th>
      <td><%= @user.last_name %></td>
    </tr>
    <tr>
      <th>Account Number</th>
      <td><%= @user.account_number %></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= @user.phone %></td>
    </tr>
    <tr>
      <th>Email Address</th>
      <td><%= @user.email %></td>
    </tr>
    <% if current_user.is_admin? -%>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <th>GUID</th>
        <td><%= @user.guid %></td>
      </tr>
      <tr>
        <th>Last login</th>
        <td><%= @user.last_login.nil? ? raw('<i>Never</i>') : @user.last_login.strftime('%b %e, %Y at %I:%M %p') %></td>
      </tr>
    <% end -%>

    <tr>
      <td>&nbsp;</td>
    </tr>

    <% if @user.can_edit?(current_user) -%>
      <tr>
        <th>Edit</th>
        <td><%= link_to 'Edit', edit_user_path(@user), class: 'btn' %></td>
      </tr>
    <% end -%>
    <% if @user.can_sudo?(current_user) -%>
      <tr>
        <th>Sudo <%= help_tip 'Temporarily assume the identity of this person. Lets you see what they see.' %></th>
        <td><%= link_to 'Assume', sudo_user_path(@user), class: 'btn btn-info' %></td>
      </tr>
    <% end -%>
    <% if current_user.is_admin? -%>
      <tr>
        <th>Admin <%= help_tip 'Grants this user Admin privileges' %></th>
        <td>
          <% if @user.is_admin? %>
            <%= link_to 'Revoke',
              toggle_admin_user_path(@user),
              method: 'post',
              data: {confirm: "Are you sure you want to revoke #{@user.display_name}'s admin privileges?"},
              class: 'btn btn-warning'
            %>
          <% else -%>
            <%= link_to 'Grant',
              toggle_admin_user_path(@user),
              method: 'post',
              data: {confirm: "Are you sure you want to grant #{@user.display_name} admin privileges?"},
              class: 'btn btn-warning'
            %>
          <% end -%>
        </td>
      </tr>
      <tr>
        <th>Delete</th>
        <td>
          <%= link_to 'Delete',
            @user,
            method: 'delete',
            data: {confirm:
'Are you sure you want to delete this user and all objects dependent on it?
This cannot be undone.'
            },
            class: 'btn btn-danger'
          %>
        </td>
      </tr>
    <% end -%>
  </table>
</div>

<div class="span8 well well-small">
  <%= render :partial => 'roles' %>
</div>