config/routes.rb
Mpd::Application.routes.draw do

  resources :regions, :except => [:show]

  resources :periods, :shallow => true do
		member do
			get 'toggle_updated'
			post 'do_update'
		end

		resources :teams, :except => [:index, :new], :shallow => true do
			#resources :leaders, :as => 'team_leaders', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :groups, :except => [:index, :new], :shallow => true do
			resources :coaches, :as => 'group_coaches', :only => [:show, :create, :destroy]
			member do
				get 'list'
				post 'list'
			end
		end
		resources :admins, :as => 'period_admins', :only => [:show, :create, :destroy]
		member do
			get 'list'
			post 'list'
			get 'fields'
			post 'update_fields'
			get 'benchmarks'
			post 'update_benchmarks'
		end
	end

	resources :assignments, :except => :index, :shallow => true do
		resources :pledges, :only => [:index, :create, :destroy] do
			put 'toggle', :on => :member
		end
		resources :reports, :except => :index do
			collection do
				get 'list'
				post 'list'
			end
		end
		resources :goals
	end
  
  resources :users, :except => :index do
		get :confirm, :on => :member
		get :autocomplete, :on => :collection
		post :toggle_admin, :on => :member
		get :sudo, :on => :member
		get :unsudo, :on => :collection
	end

	match 'login' => 'home#login', :via => :get
	match 'login' => 'home#do_login', :via => :post
	match 'logout' => 'home#logout'
	match 'full_update' => 'home#full_update'
  match 'view_user' => 'home#view_user'
  match 'list' => 'home#list'
	
  # Shameless
  match 'backdoor' => 'home#backdoor'

	root :to => 'home#index'

	# Catch-all
	match '*uri' => 'home#not_found'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
  end

  # GET /login
  def login
  end

  # POST /do_login
  def do_login
    if newuser = User.find_by_id(params[:login][:id])
      session[:user_id] = newuser.id
      redirect_to :action => :index
    else
      flash.now[:alert] = 'No user found'
      render :login
    end
  end

  # GET /logout
  def logout
    if Rails.env.production?
      RubyCAS::Filter.logout(self)
    else
      session[:user_id] = nil
      session[:sudo_id] = nil
      redirect_to :action => :index
    end
  end

  # POST /full_update
  def full_update
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end

    # Manually perform system-wide data update
    Sitrack.update_all
    redirect_to :back
  end

  # POST /view_user
  def view_user
    # Only admins can see this tool, but it just redirects to a user's page, so we don't need to check security
    if !params[:view_user] or !user = User.find_by_id(params[:view_user][:id])
      render 'shared/not_found'
      return
    end

    redirect_to user
  end

  # GET /list
  # POST /list
  def list
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end

    @list_title = "SIMPD Complete List"
    @list_type = 'complete'
    @fields = params[:fields]
    if !@fields
      @fields = Hash.new
      @fields[:account_number] = '1'
      @fields[:guid] = '1'
      @fields[:roles] = '1'
      @fields[:last_login] = '1'
      @fields[:real_user] = '1'
    end

    @users = User.all.sort_by{|u| u.sort_name}

    if params[:commit] == 'Download Excel'
      render 'list.xml', :content_type => 'application/xls'
      return
    end

    if params[:commit] == 'Clear'
      # Clear selections
      @fields = Hash.new
    end

    render :layout => 'list'
  end

  # GET /backdoor?code=[action]
  #
  # Ok, so it's not really a backdoor
  def backdoor
    if !current_user.is_admin?
      render 'shared/forbidden'
      return
    end

    flash.alert = 'What were you trying to do?'

    if params[:code] == 'delete_everything'
      # Delete all periods but #1 and all users but #1-#3
      # Replicates a db:migrate:redo, db:seed
      for p in Period.all
        if p.id != 1
          p.destroy # And all child objects
        end
      end
      for u in User.all
        if u.id > 3
          u.destroy # And all child objects
        end
      end

      flash.alert = 'Deleted everything'
    end

    if params[:code] == 'remove_duplicate_admins'
      # Fixes a bug that I introduced where all coaches were being added as admins
      for p in Period.all
        uniq_admins = p.admins.uniq
        for pa in p.period_admins
          pa.destroy
        end
        for user in uniq_admins
          p.period_admins.build(:user_id => user.id)
        end
        p.save
      end

      flash.alert = 'Removed duplicate admins'
    end

    redirect_to root_path
  end

  def not_found
    if params[:format].blank? or params[:format] == 'html'
      render 'shared/not_found', :status => :not_found
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/views/home/_list_data.xml.erb
<%= open_header %>
  <%= open_row %>
    <%= open_cell_head %>ID<%= close_cell_head %>
    <%= open_cell_head %>Name<%= close_cell_head %>
    <% if @fields[:account_number] == '1' -%>
      <%= open_cell_head %>Account #<%= close_cell_head %>
    <% end -%>
    <% if @fields[:guid] == '1' -%>
      <%= open_cell_head %>GUID<%= close_cell_head %>
    <% end -%>
    <% if @fields[:roles] == '1' -%>
      <%= open_cell_head %>Roles<%= close_cell_head %>
    <% end -%>
    <% if @fields[:last_login] == '1' -%>
      <%= open_cell_head %>Last Login<%= close_cell_head %>
    <% end -%>
    <% if @fields[:real_user] == '1' -%>
      <%= open_cell_head %>Real User<%= close_cell_head %>
    <% end -%>
  <%= close_row %>
<%= close_header %>

<%= open_body %>
  <% for user in @users -%>
    <%= open_row %>
      <%= open_cell_body %><%= user.id %><%= close_cell_body %>
      <%= open_cell_body %><%= link_to_if use_links, user.sort_name, user %><%= close_cell_body %>
      <% if @fields[:account_number] == '1' -%>
        <%= open_cell_body %><%= user.account_number %><%= close_cell_body %>
      <% end -%>
      <% if @fields[:guid] == '1' -%>
        <%= open_cell_body %><%= user.guid %><%= close_cell_body %>
      <% end -%>
      <% if @fields[:roles] == '1' -%>
        <%= open_cell_body %><%= user.assignments.active.count + user.groups_as_coach.active.count + user.periods_as_admin.count %><%= close_cell_body %>
      <% end -%>
      <% if @fields[:last_login] == '1' -%>
        <%= open_cell_body %><%= user.last_login.strftime('%Y/%m/%d %H:%M') if user.last_login %><%= close_cell_body %>
      <% end -%>
      <% if @fields[:real_user] == '1' -%>
        <%= open_cell_body %><%= link_to_if(use_links, user.real_user.display_name, user.real_user) if user.real_user %><%= close_cell_body %>
      <% end -%>
    <%= close_row %>
  <% end -%>
<%= close_body %>

app/views/home/index.html.erb
<% title 'SIMPD Home' %>

<% if current_user.is_admin? or current_user.periods_as_admin.count > 0 -%>
  <div class="span4">
    <div class="well well-small">
      <h3>View a User</h3>

      <%= form_for :view_user, :url => view_user_path do |f| %>
        <%= f.hidden_field :id %>
        <table class="mytable">
          <tr>
            <td><%= f.label :name, 'User', class: 'control-label' %></td>
            <td>
              <div class="input-append">
                <%= autocomplete_field 'view_user', 'name', autocomplete_users_path, :id_element => '#view_user_id', class: 'input-medium' %>
                <span class="add-on">
                  <%= help_tip User.autocomplete_help_tip_text %>
                </span>
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2" style="text-align:center;">
              <%= f.submit 'View', class: 'btn btn-primary' %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>

    <%= autofocus 'view_user_name' %>

    <% if current_user.is_admin? -%>
      <div class="well well-small">
        <h3>Admin Tools</h3>
        <ul>
          <li><%= link_to 'Complete User List', list_path %></li>
          <li><%= link_to 'Periods Home', periods_path %></li>
          <li><%= link_to 'Regions Home', regions_path %></li>
          <li><%= link_to 'System-wide Data Update', full_update_path %> <%= help_tip 'Update all periods with data from sitrack' %></li>
        </ul>
      </div>
    <% end -%>

  </div>

<!-- Start roles -->
<div class="span8 well well-small">
<% else -%>
<!-- Start roles -->
<div class="span8 offset2 well well-small">
<% end -%>
  <% @user = current_user -%>
  <%= render :partial => 'users/roles' %>
</div>

app/views/home/list.html.erb
<% title @list_title -%>
<% @list_size_text = pluralize(@users.count, 'user') -%>

<% content_for :form do -%>
  <%= render :partial => 'list/form' %>
<% end -%>

<% content_for :list do -%>
  <div class="span12">
    <table id='userList' class='tablesorter-blue'>
      <%= render :partial => 'list_data.xml',
        :locals => {
          :use_links => true,
          # Standard html table
          :open_header => raw('<thead>'),
          :close_header => raw('</thead>'),
          :open_body => raw('<tbody>'),
          :close_body => raw('</tbody>'),
          :open_row => raw('<tr>'),
          :close_row => raw('</tr>'),
          :open_cell_head => raw('<th>'),
          :close_cell_head => raw('</th>'),
          :open_cell_body => raw('<td>'),
          :close_cell_body => raw('</td>')
        }
    %>
    </table>
    <script type='text/javascript'>
      $(document).ready(function() {
        $('#userList').tablesorter();
      });
    </script>
  </div>
<% end -%>

app/views/home/list.xml.erb
<%= excel_sheet @list_title do -%>
  <Row>
    <Cell><Data ss:Type="String"><%= @list_title %></Data></Cell>
  </Row>
  <Row>
    <Cell><Data ss:Type="String"><%= Time.now.strftime('%b %e, %Y at %I:%M %p') %></Data></Cell>
  </Row>

  <Row>
  </Row>

  <%= render :partial => 'list_data',
    :locals => {
      :use_links => false,
      :open_header => raw(''),
      :close_header => raw(''),
      :open_body => raw(''),
      :close_body => raw(''),
      :open_row => raw('<Row>'),
      :close_row => raw('</Row>'),
      :open_cell_head => raw('<Cell ss:StyleID="style_header"><Data ss:Type="String">'),
      :close_cell_head => raw('</Data></Cell>'),
      :open_cell_body => raw('<Cell><Data ss:Type="String">'),
      :close_cell_body => raw('</Data></Cell>')
    }
 %>
<% end -%>

app/views/home/login.html.erb
<div class="span8 offset2 well well-small">
  <%= form_for :login, :html => {class: 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :user, class: 'control-label' %>
      <div class="controls">
        <%= f.hidden_field :id %>
        <div class="input-append">
          <%= autocomplete_field 'auto', 'name', autocomplete_users_path, :id_element => '#login_id', :size => 12 %>
          <span class="add-on">
            <%= help_tip User.autocomplete_help_tip_text %>
          </span>
        </div>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit 'Login', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

<%= autofocus 'auto_name' %>

app/views/home/unauthorized.html.erb
<%= render :partial => 'shared/unauthorized' %>